// Code generated by wrappergen v0.0.1. DO NOT EDIT.
package example

import i0 "github.com/hfaulds/wrappergen/timing"
import i1 "context"

func NewExampleTimer(p0 Example, p1 i0.Timing) Example {
	return timeExample{
		wrapped: p0,
		timing:  p1,
	}
}

type timeExample struct {
	wrapped Example
	timing  i0.Timing
}

func (t timeExample) Test(p0 i1.Context, p1 int64) error {
	timer := t.timing.Timer()
	defer timer.End(p0, "Test")
	return t.wrapped.Test(p0, p1)
}
