// Code generated by wrappergen v0.0.1. DO NOT EDIT.
package example

import i0 "github.com/hfaulds/wrappergen/tracing"
import i1 "context"

func NewExampleTracer(p0 Example, p1 i0.Tracing) Example {
	return traceExample{
		wrapped: p0,
		trace:   p1,
	}
}

type traceExample struct {
	wrapped Example
	trace   i0.Tracing
}

func (t traceExample) Test(p0 i1.Context, p1 int64) error {
	ctx, span := t.trace.ChildSpan(p0, t.trace.OpName("Test"))
	defer span.Finish()
	r0 := t.wrapped.Test(ctx, p1)
	return span.WithError(r0)
}
